[versions]
agp            = "8.4.0"
kotlin         = "1.9.23"
coreKtx        = "1.13.1"
appcompat      = "1.7.0"
material       = "1.12.0"
lifecycle      = "2.8.1"
coroutines     = "1.8.1"
recyclerview   = "1.3.2"

[libraries]
androidx-core-ktx          = { group = "androidx.core",        name = "core-ktx",              version.ref = "coreKtx"      }
androidx-appcompat         = { group = "androidx.appcompat",   name = "appcompat",             version.ref = "appcompat"    }
material                   = { group = "com.google.android.material", name = "material",        version.ref = "material"     }
lifecycle-viewmodel-ktx    = { group = "androidx.lifecycle",   name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle"  }
lifecycle-livedata-ktx     = { group = "androidx.lifecycle",   name = "lifecycle-livedata-ktx",  version.ref = "lifecycle"  }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-recyclerview      = { group = "androidx.recyclerview", name = "recyclerview",          version.ref = "recyclerview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp"    }
kotlin-android      = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
